website_port: 3000
website_deploy_directory: c:\iisexpress\ConUniv
website_port_load_balanced_1: 4000
website_deploy_directory_load_balanced_1: c:\iisexpress\ConUniv_4000
website_port_load_balanced_2: 5000
website_deploy_directory_load_balanced_2: c:\iisexpress\ConUniv_5000
solution_name: ConUniv #just the name, no .sln extension
mvc_project: ..\ConUniv #just the folder name, no .csproj extension
test_project: ConUniv.Tests #just the folder name, no .csproj extension
test_runner: ./packages/nspec.1.0.1/tools/NSpecRunner.exe
iis_express: C:\Program Files (x86)\IIS Express
database_name: ConUniv
database_server: (local)
